# Generated by Django 2.2.6 on 2019-10-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191004_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('region', models.CharField(max_length=100, verbose_name='Região')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Produtora',
                'verbose_name_plural': 'Produtoras',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(default=1, on_delete='cascade', to='catalog.Producer', verbose_name='Produtora'),
            preserve_default=False,
        ),
    ]
