# Generated by Django 2.2.6 on 2019-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191007_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='medida',
            field=models.CharField(default=1, max_length=5, verbose_name='Medida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quant',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
